# Generated by Django 5.0.6 on 2024-06-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_quote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='quote',
            field=models.TextField(blank=True, null=True),
        ),
    ]
