# Generated by Django 5.0.6 on 2024-06-25 23:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blog_is_quote_blog_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='quote',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
