# Generated by Django 5.0.6 on 2024-06-26 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tag_blog_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='is_quote',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='quote',
        ),
    ]
