# Generated by Django 5.0.6 on 2024-06-26 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='ads_content',
            new_name='top_services',
        ),
    ]
