# Generated by Django 5.0.6 on 2024-06-26 12:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_ads_content_about_top_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social', models.CharField(choices=[('facebook', 'facebook'), ('instagram', 'instagram'), ('linkedin', 'linkedin'), ('tiktok', 'tiktok'), ('youtube', 'youtube'), ('telegram', 'telegram'), ('whatsapp', 'whatsapp')], max_length=50)),
                ('link', models.URLField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Social Accounts',
            },
        ),
        migrations.CreateModel(
            name='WebsiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Əlaqə E-poçt')),
                ('address', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Adres')),
                ('work_hours', models.CharField(blank=True, max_length=300, null=True)),
                ('map', models.TextField(blank=True, null=True, verbose_name='Map')),
                ('header_social_accounts', models.ManyToManyField(blank=True, related_name='settings', to='core.socialaccount', verbose_name='Social Accounts')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
