# Generated by Django 5.0.6 on 2024-06-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_contact_alter_team_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
    ]
